import type { MockMarket } from './mock-catalog-types'

export const MOCK_MARKETS: MockMarket[] = [
  {
    code: 'AT',
    country: 'Austria',
    currency: 'EUR',
    rate: 0.92,
    taxRate: 0.2,
    taxIncluded: true,
    shipping: 5.9,
    deliveryDays: [2, 5],
  },
  {
    code: 'AU',
    country: 'Australia',
    currency: 'AUD',
    rate: 1.52,
    taxRate: 0.1,
    taxIncluded: true,
    shipping: 12,
    deliveryDays: [3, 7],
  },
  {
    code: 'BE',
    country: 'Belgium',
    currency: 'EUR',
    rate: 0.92,
    taxRate: 0.21,
    taxIncluded: true,
    shipping: 5.5,
    deliveryDays: [2, 5],
  },
  {
    code: 'CA',
    country: 'Canada',
    currency: 'CAD',
    rate: 1.36,
    taxRate: 0.13,
    taxIncluded: false,
    shipping: 9.5,
    deliveryDays: [3, 7],
  },
  {
    code: 'CH',
    country: 'Switzerland',
    currency: 'CHF',
    rate: 0.9,
    taxRate: 0.081,
    taxIncluded: true,
    shipping: 8.9,
    deliveryDays: [2, 6],
  },
  {
    code: 'CZ',
    country: 'Czechia',
    currency: 'CZK',
    rate: 23.1,
    taxRate: 0.21,
    taxIncluded: true,
    shipping: 109,
    deliveryDays: [2, 5],
  },
  {
    code: 'DE',
    country: 'Germany',
    currency: 'EUR',
    rate: 0.92,
    taxRate: 0.19,
    taxIncluded: true,
    shipping: 4.9,
    deliveryDays: [2, 4],
  },
  {
    code: 'DK',
    country: 'Denmark',
    currency: 'DKK',
    rate: 6.87,
    taxRate: 0.25,
    taxIncluded: true,
    shipping: 49,
    deliveryDays: [2, 5],
  },
  {
    code: 'ES',
    country: 'Spain',
    currency: 'EUR',
    rate: 0.92,
    taxRate: 0.21,
    taxIncluded: true,
    shipping: 5.9,
    deliveryDays: [2, 6],
  },
  {
    code: 'FI',
    country: 'Finland',
    currency: 'EUR',
    rate: 0.92,
    taxRate: 0.255,
    taxIncluded: true,
    shipping: 6.9,
    deliveryDays: [3, 7],
  },
  {
    code: 'FR',
    country: 'France',
    currency: 'EUR',
    rate: 0.92,
    taxRate: 0.2,
    taxIncluded: true,
    shipping: 5.9,
    deliveryDays: [2, 5],
  },
  {
    code: 'GB',
    country: 'United Kingdom',
    currency: 'GBP',
    rate: 0.79,
    taxRate: 0.2,
    taxIncluded: true,
    shipping: 4.5,
    deliveryDays: [2, 5],
  },
  {
    code: 'HU',
    country: 'Hungary',
    currency: 'HUF',
    rate: 358,
    taxRate: 0.27,
    taxIncluded: true,
    shipping: 1890,
    deliveryDays: [2, 6],
  },
  {
    code: 'IE',
    country: 'Ireland',
    currency: 'EUR',
    rate: 0.92,
    taxRate: 0.23,
    taxIncluded: true,
    shipping: 6.5,
    deliveryDays: [2, 6],
  },
  {
    code: 'IT',
    country: 'Italy',
    currency: 'EUR',
    rate: 0.92,
    taxRate: 0.22,
    taxIncluded: true,
    shipping: 5.9,
    deliveryDays: [2, 6],
  },
  {
    code: 'JP',
    country: 'Japan',
    currency: 'JPY',
    rate: 149,
    taxRate: 0.1,
    taxIncluded: true,
    shipping: 900,
    deliveryDays: [2, 6],
  },
  {
    code: 'NL',
    country: 'Netherlands',
    currency: 'EUR',
    rate: 0.92,
    taxRate: 0.21,
    taxIncluded: true,
    shipping: 4.9,
    deliveryDays: [1, 4],
  },
  {
    code: 'NO',
    country: 'Norway',
    currency: 'NOK',
    rate: 10.6,
    taxRate: 0.25,
    taxIncluded: true,
    shipping: 79,
    deliveryDays: [3, 7],
  },
  {
    code: 'NZ',
    country: 'New Zealand',
    currency: 'NZD',
    rate: 1.64,
    taxRate: 0.15,
    taxIncluded: true,
    shipping: 14,
    deliveryDays: [3, 8],
  },
  {
    code: 'PL',
    country: 'Poland',
    currency: 'PLN',
    rate: 3.98,
    taxRate: 0.23,
    taxIncluded: true,
    shipping: 14.99,
    deliveryDays: [1, 4],
  },
  {
    code: 'PT',
    country: 'Portugal',
    currency: 'EUR',
    rate: 0.92,
    taxRate: 0.23,
    taxIncluded: true,
    shipping: 6.5,
    deliveryDays: [2, 7],
  },
  {
    code: 'RO',
    country: 'Romania',
    currency: 'RON',
    rate: 4.58,
    taxRate: 0.19,
    taxIncluded: true,
    shipping: 24,
    deliveryDays: [2, 6],
  },
  {
    code: 'SE',
    country: 'Sweden',
    currency: 'SEK',
    rate: 10.4,
    taxRate: 0.25,
    taxIncluded: true,
    shipping: 59,
    deliveryDays: [2, 6],
  },
  {
    code: 'SK',
    country: 'Slovakia',
    currency: 'EUR',
    rate: 0.92,
    taxRate: 0.23,
    taxIncluded: true,
    shipping: 5.5,
    deliveryDays: [2, 5],
  },
  {
    code: 'US',
    country: 'United States',
    currency: 'USD',
    rate: 1,
    taxRate: 0.0825,
    taxIncluded: false,
    shipping: 7.99,
    deliveryDays: [2, 6],
  },
]
