import type { MockProductTemplate } from './mock-catalog-types'

export const MOCK_TEMPLATES: MockProductTemplate[] = [
  {
    name: 'AeroRun Daily 5',
    category: 'Running shoes',
    keywords: ['shoes', 'running', 'sneakers', 'road', 'wide'],
    basePrice: 95,
    brand: 'StrideLab',
    description: 'Cushioned everyday road runner with a breathable engineered-mesh upper.',
    specifications: { weight: '268 g', drop: '8 mm', fit: 'regular and wide', surface: 'road' },
  },
  {
    name: 'TrailPeak Grip Pro',
    category: 'Trail shoes',
    keywords: ['shoes', 'running', 'trail', 'hiking', 'waterproof'],
    basePrice: 138,
    brand: 'Northpath',
    description: 'Protective trail shoe with deep lugs and a water-resistant upper.',
    specifications: { weight: '312 g', drop: '6 mm', lugs: '5 mm', surface: 'trail' },
  },
  {
    name: 'QuietWave ANC 4',
    category: 'Headphones',
    keywords: ['headphones', 'audio', 'wireless', 'bluetooth', 'noise cancelling'],
    basePrice: 249,
    brand: 'SonicArc',
    description: 'Over-ear wireless headphones with adaptive active noise cancellation.',
    specifications: {
      battery: '38 hours',
      codec: 'AAC and LDAC',
      weight: '254 g',
      charging: 'USB-C',
    },
  },
  {
    name: 'PocketBeat Buds S',
    category: 'Earbuds',
    keywords: ['earbuds', 'audio', 'wireless', 'bluetooth', 'sports'],
    basePrice: 119,
    brand: 'SonicArc',
    description: 'Compact IPX5 earbuds with multipoint pairing and transparency mode.',
    specifications: {
      battery: '8 + 24 hours',
      protection: 'IPX5',
      microphones: '6',
      charging: 'USB-C and Qi',
    },
  },
  {
    name: 'WorkBook Air 14',
    category: 'Laptop',
    keywords: ['laptop', 'computer', 'work', 'student', 'ultrabook'],
    basePrice: 899,
    brand: 'Nova Computing',
    description: 'Portable 14-inch productivity laptop with all-day battery life.',
    specifications: {
      processor: '8-core N2',
      memory: '16 GB',
      storage: '512 GB SSD',
      display: '14-inch 2.5K',
    },
  },
  {
    name: 'CreatorBook Studio 16',
    category: 'Laptop',
    keywords: ['laptop', 'computer', 'creator', 'gaming', 'video editing'],
    basePrice: 1699,
    brand: 'Nova Computing',
    description: 'High-performance laptop for editing, 3D work, and demanding applications.',
    specifications: {
      processor: '12-core N2 Pro',
      memory: '32 GB',
      storage: '1 TB SSD',
      graphics: 'Studio 4070 8 GB',
    },
  },
  {
    name: 'PixelOne 9 256GB',
    category: 'Smartphone',
    keywords: ['phone', 'smartphone', 'android', 'camera', '5g'],
    basePrice: 699,
    brand: 'PixelOne',
    description: '5G smartphone with a bright OLED display and stabilized main camera.',
    specifications: {
      storage: '256 GB',
      display: '6.3-inch OLED',
      camera: '50 MP',
      protection: 'IP68',
    },
  },
  {
    name: 'ViewMax 27Q',
    category: 'Monitor',
    keywords: ['monitor', 'display', 'gaming', 'office', 'usb-c'],
    basePrice: 329,
    brand: 'ClearView',
    description: 'Color-calibrated 27-inch monitor with USB-C power delivery.',
    specifications: {
      resolution: '2560 × 1440',
      refresh: '165 Hz',
      panel: 'IPS',
      ports: 'USB-C, HDMI, DisplayPort',
    },
  },
  {
    name: 'TypeCraft 75',
    category: 'Keyboard',
    keywords: ['keyboard', 'mechanical', 'gaming', 'wireless', 'office'],
    basePrice: 149,
    brand: 'KeyFoundry',
    description: 'Hot-swappable 75% mechanical keyboard with three connection modes.',
    specifications: {
      switches: 'tactile',
      layout: '75%',
      connection: '2.4 GHz, Bluetooth, USB-C',
      battery: '4000 mAh',
    },
  },
  {
    name: 'BaristaFlow 12',
    category: 'Coffee maker',
    keywords: ['coffee', 'espresso', 'coffee maker', 'kitchen', 'barista'],
    basePrice: 479,
    brand: 'Daily Roast',
    description: 'Thermoblock espresso machine with an integrated conical-burr grinder.',
    specifications: { pressure: '15 bar', grinder: '30 settings', tank: '2 L', power: '1450 W' },
  },
  {
    name: 'GlowBalance Routine Set',
    category: 'Skincare',
    keywords: ['skincare', 'beauty', 'serum', 'moisturizer', 'sensitive skin'],
    basePrice: 72,
    brand: 'Kindred Skin',
    description: 'Fragrance-free cleanser, serum, and moisturizer routine for sensitive skin.',
    specifications: {
      products: '3 full-size items',
      skinType: 'normal to sensitive',
      fragrance: 'none',
      testing: 'dermatologist tested',
    },
  },
  {
    name: 'CleanBot L8',
    category: 'Robot vacuum',
    keywords: ['vacuum', 'robot', 'cleaner', 'home', 'pet hair'],
    basePrice: 549,
    brand: 'HomePilot',
    description: 'LiDAR robot vacuum with room mapping and automatic carpet boost.',
    specifications: { suction: '7000 Pa', runtime: '180 minutes', mapping: 'LiDAR', bin: '450 ml' },
  },
  {
    name: 'PawServe Smart 5L',
    category: 'Pet feeder',
    keywords: ['pet', 'dog', 'cat', 'feeder', 'automatic', 'smart home'],
    basePrice: 139,
    brand: 'Companion Tech',
    description: 'App-connected automatic pet feeder with portion scheduling and backup power.',
    specifications: {
      capacity: '5 L',
      portions: '1–10 per meal',
      connectivity: '2.4 GHz Wi-Fi',
      backup: '3 D-cell batteries',
    },
  },
  {
    name: 'StormShell 3L',
    category: 'Rain jacket',
    keywords: ['jacket', 'clothing', 'rain', 'waterproof', 'hiking'],
    basePrice: 189,
    brand: 'Northpath',
    description: 'Three-layer waterproof shell designed for wet and windy conditions.',
    specifications: {
      waterproofing: '20,000 mm',
      breathability: '15,000 g/m²',
      fit: 'unisex',
      sizes: 'XS–XXL',
    },
  },
  {
    name: 'TorqueDrive 18V Kit',
    category: 'Power tools',
    keywords: ['tools', 'drill', 'driver', 'diy', 'construction', 'cordless'],
    basePrice: 179,
    brand: 'ForgeWorks',
    description: 'Cordless drill-driver kit for home repairs, assembly, and light construction.',
    specifications: {
      voltage: '18 V',
      torque: '65 Nm',
      batteries: '2 × 2.0 Ah',
      chuck: '13 mm keyless',
    },
  },
  {
    name: 'TransitPack 28',
    category: 'Backpack',
    keywords: ['backpack', 'bag', 'travel', 'laptop', 'carry on'],
    basePrice: 129,
    brand: 'CarryWorks',
    description: 'Clamshell travel backpack with a suspended laptop compartment.',
    specifications: {
      capacity: '28 L',
      laptop: 'up to 16 inches',
      material: 'recycled nylon',
      weight: '1.1 kg',
    },
  },
  {
    name: 'NestView Baby Pro',
    category: 'Baby monitor',
    keywords: ['baby', 'monitor', 'nursery', 'camera', 'parenting', 'video'],
    basePrice: 199,
    brand: 'NestView',
    description: 'Encrypted video baby monitor with a dedicated parent display and night vision.',
    specifications: {
      video: '2K camera',
      display: '5-inch parent unit',
      range: '300 m line of sight',
      features: 'night vision and temperature alerts',
    },
  },
  {
    name: 'FitTrack Active 3',
    category: 'Smartwatch',
    keywords: ['watch', 'smartwatch', 'fitness', 'running', 'gps'],
    basePrice: 229,
    brand: 'PulseMetric',
    description: 'GPS fitness watch with recovery guidance and offline route tracking.',
    specifications: {
      battery: '10 days',
      protection: '5 ATM',
      positioning: 'dual-band GPS',
      display: 'AMOLED',
    },
  },
  {
    name: 'GameBox Series V',
    category: 'Game console',
    keywords: ['console', 'gaming', 'video games', 'controller', '4k'],
    basePrice: 499,
    brand: 'GameBox',
    description: 'Current-generation home console for 4K gaming and media playback.',
    specifications: {
      storage: '1 TB SSD',
      output: 'up to 4K 120 Hz',
      controller: 'included',
      drive: 'disc',
    },
  },
  {
    name: 'TabCanvas 11',
    category: 'Tablet',
    keywords: ['tablet', 'student', 'drawing', 'android', 'portable'],
    basePrice: 449,
    brand: 'PixelOne',
    description: 'Portable 11-inch tablet with pressure-sensitive pen support.',
    specifications: {
      storage: '256 GB',
      display: '11-inch 120 Hz',
      battery: '12 hours',
      pen: 'supported, sold separately',
    },
  },
]
